services:
  suntoday:
    restart: always
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SUNTODAY_SAVE_DIRECTORY=${SUNTODAY_SAVE_DIRECTORY}
    volumes:
      # This should be changed to point towards the final location for the images on the VM
      # The left side is the host path, the right side is the container path
      - ./images:${SUNTODAY_SAVE_DIRECTORY}:Z
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: suntoday_user
      POSTGRES_DB: suntoday
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suntoday_user -d suntoday"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    volumes:
      - ./pgdata:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
