[tox]
min_version = 4.0
envlist =
    py{,-online,-figure}
    py-figure-generate
    codestyle

[testenv]
allowlist_externals=
    /bin/bash
    /usr/bin/bash
description =
    run tests
    online: runs tests that require remote data
    figure: compares deterministic figure baselines
    figure-generate: generates figure baselines, including live remote-data figures
setenv =
    COLUMNS = 180
    PYTEST_COMMAND = pytest -vvv -s -raR
    SUNTODAY_TEST_ENV = True
passenv =
    SUNTODAY_JSOC_USER
    SUNTODAY_JSOC_PASSWORD
deps =
    -rrequirements.txt
    -rrequirements-test.txt
commands =
    pip freeze --all --no-input
    !figure-!online: {env:PYTEST_COMMAND} -n auto -m "not mpl_image_compare and not remote_data" {posargs}
    online: {env:PYTEST_COMMAND} --remote-data=any -m "remote_data and not mpl_image_compare" {posargs}
    figure: /bin/bash -c "mkdir -p ./figure_test_images; python -c 'import matplotlib as mpl; print(mpl.ft2font.__file__, mpl.ft2font.__freetype_version__, mpl.ft2font.__freetype_build_type__)' > ./figure_test_images/figure_version_info.txt"
    figure-!generate: {env:PYTEST_COMMAND} -n auto -m "mpl_image_compare and not remote_data" --mpl {posargs}
    figure-generate: {env:PYTEST_COMMAND} -n auto --remote-data=any -m "mpl_image_compare" --mpl --mpl-generate-path="src/suntoday/tests/baseline/" {posargs}

[testenv:py-figure-generate]
description = Generate figure baselines, including live remote-data figures.

[testenv:codestyle]
pypi_filter =
skip_install = true
description = Run all style and file checks with pre-commit
deps =
    pre-commit
commands =
    pre-commit install-hooks
    pre-commit run --all-files
